### ISSUE TITLE
Number Guessing Game: A Fun and Challenging Java Program kindly assigned to me

### ISSUE THREAD

**Issue by Mudassir97** [whitedevil9911/Hacktoberfest_2024#73]
hey @whitedevil9911 

This Java program is a classic number guessing game. The computer generates a random number between 1 and 100, and the player has to guess it. The program provides feedback to the player, indicating whether their guess is too high or too low. The game continues until the player guesses the correct number. Try your luck and see how many attempts it takes you to crack the code!

kindly assigned to me this under #HacktoberFest2024

**Comment by whitedevil9911** [comment]
Done. ✅ You can contribute the code in this Hacktoberfest24 


And you can also contribute https://github.com/hari7261/Hacktoberfest-2024

On this repo

**Comment by whitedevil9911** [comment]
Done ✅ you can contribute your code into Hacktoberfest24 

Just send me the pull request I'll be waiting for you there 
Thank You !.

**Comment by hari7261** [comment]
> Done ✅ you can contribute your code into Hacktoberfest24
> 
> Just send me the pull request I'll be waiting for you there Thank You !.

You can contribute in  @hari7261  repo link   =  https://github.com/hari7261/Hacktoberfest-2024
